"""Generates source/MarkdownEntities.pas from the WHATWG HTML5 entity table.

Usage:
    python tools/GenerateEntities.py [path/to/entities.json]

Without an argument the table is downloaded from
https://html.spec.whatwg.org/entities.json. Only the entities terminated by ';'
are kept (CommonMark recognizes entity references only with the semicolon).
The output is a sorted array searched with a binary search (Delphi XE3 safe).
"""
import json
import os
import sys
import urllib.request

URL = "https://html.spec.whatwg.org/entities.json"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "source", "MarkdownEntities.pas")

HEADER = """{******************************************************************************}
{                                                                              }
{       MarkDown Processor                                                     }
{       HTML5 named character references                                       }
{                                                                              }
{       GENERATED by tools/GenerateEntities.py from the WHATWG table           }
{       https://html.spec.whatwg.org/entities.json - do not edit by hand.     }
{                                                                              }
{******************************************************************************}
{                                                                              }
{  Licensed under the Apache License, Version 2.0 (the "License");             }
{  you may not use this file except in compliance with the License.            }
{  You may obtain a copy of the License at                                     }
{                                                                              }
{      http://www.apache.org/licenses/LICENSE-2.0                              }
{                                                                              }
{  Unless required by applicable law or agreed to in writing, software         }
{  distributed under the License is distributed on an "AS IS" BASIS,           }
{  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    }
{  See the License for the specific language governing permissions and         }
{  limitations under the License.                                              }
{                                                                              }
{******************************************************************************}
unit MarkdownEntities;

interface

/// <summary>Looks up a named character reference. Name is without '&' and ';'
/// (case sensitive). Returns False when the name is not an HTML5 entity.</summary>
function LookupEntity(const Name: string; out Value: string): Boolean;

implementation

uses
  System.SysUtils;

type
  TEntity = record
    Name: string;
    Value: string;
  end;

const
"""

FOOTER = """
function LookupEntity(const Name: string; out Value: string): Boolean;
var
  Lo, Hi, Mid, Cmp: Integer;
begin
  Lo := Low(Entities);
  Hi := High(Entities);
  while Lo <= Hi do
  begin
    Mid := (Lo + Hi) div 2;
    Cmp := CompareStr(Entities[Mid].Name, Name);
    if Cmp = 0 then
    begin
      Value := Entities[Mid].Value;
      Exit(True);
    end;
    if Cmp < 0 then
      Lo := Mid + 1
    else
      Hi := Mid - 1;
  end;
  Value := '';
  Result := False;
end;

end.
"""


def delphi_string(value):
    units = value.encode("utf-16-le")
    codes = [int.from_bytes(units[i:i + 2], "little") for i in range(0, len(units), 2)]
    return "".join("#$%.4X" % c for c in codes)


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as f:
            table = json.load(f)
    else:
        with urllib.request.urlopen(URL) as response:
            table = json.loads(response.read().decode("utf-8"))
    entries = sorted(
        (name[1:-1], data["characters"])
        for name, data in table.items()
        if name.startswith("&") and name.endswith(";"))
    lines = []
    for i, (name, value) in enumerate(entries):
        sep = "," if i < len(entries) - 1 else ""
        lines.append("    (Name: '%s'; Value: %s)%s" % (name, delphi_string(value), sep))
    with open(TARGET, "w", encoding="utf-8", newline="\r\n") as out:
        out.write(HEADER)
        out.write("  Entities: array[0..%d] of TEntity = (\n" % (len(entries) - 1))
        out.write("\n".join(lines))
        out.write("\n  );\n")
        out.write(FOOTER)
    print("%d entities written to %s" % (len(entries), TARGET))


if __name__ == "__main__":
    main()
